apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "scope.fullname" . }}-default.appscope.io
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "scope.fullname" . }}-
  labels:
  {{- include "scope.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: '{{ include "scope.fullname" . }}-scope'
      namespace: '{{ .Release.Namespace }}'
      path: /mutate
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: scope.default.appscope.io
  namespaceSelector:
    matchLabels:
      scope: enabled
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None