apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "scope.fullname" . }}-webhook-cert-cluster-role-binding
  labels:
  {{- include "scope.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "scope.fullname" . }}-webhook-cert-cluster-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "scope.fullname" . }}-webhook-cert-sa'
  namespace: '{{ .Release.Namespace }}'